### PR TITLE
Extended ToPayload

### PR DESCRIPTION
**Pull request by elij**
Added support for IfInfo as a payload

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
Thanks for your help on improving this :)

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@polachok do you have any idea why Travis is not building anymore? I can not merge without a Travis build :/

**Comment by polachok** [comment]
It says "abuse detected" on this page: https://travis-ci.org/polachok/pnetlink/requests. I'll contact support.

**Comment by bkchr** [comment]
Ty

**Comment by polachok** [comment]
-- Please reply above this line --


Hi Alexander,

Thanks for writing in and sorry for the troubles.

I've been looking into these rejected requests and I see that the lypy
organization nor any of its members have been never logged into Travis
CI and this is why we are currently blocking these requests that come
from lypy's fork of your pnetlink repository. Sorry for the
inconvenience.

We are looking into fixing this false positive in our abuse detection
system, as we don't feel that an organization or account should have
to create a Travis account when working with another project that is
using Travis CI.

To sort this out in the meantime, do you know who manages this
organization and do you think one of their members (such as @elij, who
opened the PRs) could try to log into Travis CI at least once at
https://travis-ci.org/ [1] and try closing and reopen one of the
rejected Pull Requests?

Please let us know the result and we would be happy to have another
look if it's still not working.

Thanks in advance and have a great day!

**Comment by bkchr** [comment]
Thanks for being that patient @elij!

**Pull request merged**
